# mise global configuration

[tools]
# Node.js - プロジェクトごとに指定がない場合のデフォルトバージョン
node = "lts"

# Python
python = "3.12"

# Go
go = "latest"

# Rust
rust = "stable"

# 必要に応じて他のツールを追加
# java = "21"
# ruby = "3.3"

[env]
# グローバル環境変数
EDITOR = "nvim"
LANG = "ja_JP.UTF-8"

# Development
HOMEBREW_NO_AUTO_UPDATE = "1"

[tasks.update]
description = "mise自体とツールをアップデート"
run = "mise self-update && mise upgrade"

[tasks.doctor]
description = "mise環境の診断"
run = "mise doctor"

[tasks.clean]
description = "未使用のバージョンをクリーンアップ"
run = "mise prune"

[settings]
idiomatic_version_file_enable_tools = []
